CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) UNIQUE NOT NULL,
    email VARCHAR(512) UNIQUE NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS location (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    lat double NOT NULL,
    lon double NOT NULL,
     CONSTRAINT pk_location PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) UNIQUE NOT NULL,
    CONSTRAINT pk_category PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS compilationService (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pinned boolean,
    title VARCHAR(255) NOT NULL,
    CONSTRAINT pk_compilation PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(1000) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    category BIGINT NOT NULL REFERENCES category (id),
    confirmed_requests INT,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    published_on TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    event_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    initiator BIGINT NOT NULL REFERENCES users (id),
    location BIGINT NOT NULL REFERENCES location (id),
    compilationService BIGINT REFERENCES compilationService(id),
    paid boolean NOT NULL,
    participant_limit INT,
    request_moderation boolean,
    state text NOT NULL,
    title VARCHAR(10000) NOT NULL,
    views INT,
    CONSTRAINT pk_event PRIMARY KEY (id)
    );

CREATE TABLE IF NOT EXISTS request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    event BIGINT NOT NULL REFERENCES event (id),
    requester BIGINT NOT NULL REFERENCES users (id),
    created TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status text NOT NULL,
    CONSTRAINT pk_request PRIMARY KEY (id)
);
