version: '3.1'
services:
  stats-server:
    build: stat/stat-server
    container_name: stats
    image: stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=root
        SPRING_DATASOURCE_PASSWORD=root
      - TZ=GMT

  stats-db:
    image: postgres:14-alpine
    container_name: stats-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - TZ=GMT
